# Cleaning Data

In [40]:
import pandas as pd
import numpy as np

In [21]:
df = pd.read_excel("Datasets/signup.xlsx")
df

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0  b@gmail.com  2024-01-06
4     NaN   NaN          NaN         NaT
5    John  21.0  j@gmail.com  2024-01-08
6   Alice  29.0  a@gmail.com  2024-01-02
7  Carlos  41.0          NaN  2024-01-05

<h2 style = "color:#4fd4ff" >Detecting Missing Values</h2>

Before you can fix missing data, you need to find it. <br>
Pandas represents a missing value as NaN (Not a Number). <br>
isnan() returns a same-shaped DataFrame of True/False. <br>
Returns True whenever a cell is missing.

In [5]:
df.isna()

    name    age  email  signup_date
0  False  False  False        False
1  False   True  False         True
2  False  False   True        False
3   True  False   True        False

Knowing that missing values exist is step 1. <br>
Knowing exactly how many, and in which columns, is what turns that into a plan. <br>
Chaining .sum() onto .isna() returns the count of missing values in each column.

In [17]:
df.isna().sum()

name           1
age            1
email          2
signup_date    1
dtype: int64

In [18]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False) # Percentage missing per column

email          50.0
name           25.0
age            25.0
signup_date    25.0
dtype: float64

In [21]:
df.isna().sum().sum() # Total missing cells in the entire DataFrame

np.int64(5)

In [22]:
df.info() # shows non-null count per column which is a mirror image of this command df.isna().sum()

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   name         3 non-null      str
 1   age          3 non-null      float64
 2   email        2 non-null      str
 3   signup_date  3 non-null      datetime64[us]
dtypes: datetime64[us](1), float64(1), str(2)
memory usage: 260.0 bytes

<h2 style = "color:#4fd4ff" >Dropping Rows or Columns - dropna()</h2>

In [23]:
df.dropna() # Drops any row with at least one missing value

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02

In [8]:
df.dropna(axis = 1) # Drops any column with a missing value instead of rows

  signup_date
0  2024-01-02
1  2024-01-03
2  2024-01-05
3  2024-01-06

In [13]:
df.dropna(how = "all") # Only drops a row if all its values are missing

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0          NaN  2024-01-06
5    John  21.0  j@gmail.com  2024-01-08

In [18]:
df.dropna(subset = ["name", "email"]) # Only considers missing values in specific columns

    name   age        email signup_date
0  Alice  29.0  a@gmail.com  2024-01-02
1    Bob   NaN  b@gmail.com  2024-01-03
5   John  21.0  j@gmail.com  2024-01-08

<h2 style = "color:#4fd4ff" >Duplicate Rows</h2>

Data collected from multiple sources - for example a form resumbited, 2 systems  merged, a scrapper run twice, almost always produces duplicate rows.<br>
.duplicated() flags them <br>
.drop_duplicates() removes them

In [5]:
#df = pd.read_excel("Datasets/kids_records.xlsx")
#df

In [11]:
df.isna().sum()

name           2
age            2
email          4
signup_date    1
dtype: int64

In [12]:
(df.isna().sum()/len(df) * 100).sort_values(ascending = False)

email          50.0
name           25.0
age            25.0
signup_date    12.5
dtype: float64

In [26]:
df = df.dropna(how = "all")

In [15]:
df.dropna(subset = ["name"])

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
5    John  21.0  j@gmail.com  2024-01-08
6   Alice  29.0  a@gmail.com  2024-01-02
7  Carlos  41.0          NaN  2024-01-05

In [22]:
df.duplicated().sum()

np.int64(2)

In [23]:
df.drop_duplicates()

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
2  Carlos  41.0          NaN  2024-01-05
3     NaN  35.0  b@gmail.com  2024-01-06
4     NaN   NaN          NaN         NaT
5    John  21.0  j@gmail.com  2024-01-08

In [29]:
dup_emails = df[df.duplicated(subset = ["email"], keep = False)].sort_values("email")
print(dup_emails)

     name   age        email signup_date
0   Alice  29.0  a@gmail.com  2024-01-02
6   Alice  29.0  a@gmail.com  2024-01-02
1     Bob   NaN  b@gmail.com  2024-01-03
3     NaN  35.0  b@gmail.com  2024-01-06
2  Carlos  41.0          NaN  2024-01-05
7  Carlos  41.0          NaN  2024-01-05

In [74]:
students_df = pd.read_excel("Datasets/school_kids_100.xlsx")

In [76]:
students_df = students_df.dropna(how = "all")

students_df.duplicated().sum()

students_df = students_df.drop_duplicates()

students_df.duplicated().sum()

students_df = students_df.dropna(subset = ["student_id"])
students_df

print(len(students_df))

students_df["gender"] = students_df["gender"].str.strip().str.upper().map({
    "m" : "Male",
    "M" : "Male",
    "MALE" : "Male",
    "male" : "Male",
    "female" : "Female",
    "FEMALE" : "Female", 
    "f" : "Female",
    "F" : "Female"
})

age_to_grade = {
    8 : "Grade 2",
    9 : "Grade 3",
    10 : "Grade 4",
    11 : "Grade 5",
    12 : "Grade 6",
    13 : "Grade 7",
    14 : "Grade 8",
    15 : "Grade 9", 
    16 : "Grade 10",
    17 : "Grade 11" 
}

students_df["grade"] = np.where(students_df["age"] <= 7, "Grade 1", students_df["grade"])

students_df["grade"] = np.where(students_df["age"] > 17, "Grade 12", students_df["grade"])

students_df["grade"] = students_df["age"].map(age_to_grade).fillna(students_df["grade"])

students_df["age_num"] = students_df["age"]
students_df = students_df.sort_values("age_num")
students_df = students_df.drop(columns = "age_num")
students_df["age"] = students_df["age"].abs()
students_df = students_df[-students_df["age"].isin([0, 150])]

students_df.head(31)

88

,student_id,first_name,last_name,gender,age,grade,email,phone_number,enrollment_date,gpa,city,guardian_name,attendance_rate
5,STU01689,Jeremiah,Lawson,Female,5.0,Grade 1,jeremiahl40@gmail.com,(97) 5072407,2018-05-26,3.65,Lusaka,Christina Lawson,62.1
82,STU01110,Jeffrey,Davis,Male,5.0,Grade 1,jeffrey.davis931@yahoo.com,+260-96-9072838,2020/09/18,1.52,NaN,Morgan Davis,63.5
24,STU00282,Amanda,Stone,Female,6.0,Grade 1,amanda.stone152@yahoo.com,(96) 8304611,NaN,3.73,Livingstone,Nicholas Stone,87.5
35,STU02825,Jason,Gutierrez,Male,6.0,Grade 1,jason.gutierrez701@outlook.com,+260-97-6862340,03-22-2024,2.82,lusaka,Grace Gutierrez,95.1
66,STU03699,Scott,Fletcher,Female,6.0,Grade 1,scott.fletcher629@gmail.com,+260-95-4915203,09/05/2022,2.32,SOLWEZI,Melissa Fletcher,85.0
20,STU02917,Joseph,Wilson,Male,6.0,Grade 1,josephw7@yahoo.com,(97) 1508563,02/04/2021,2.72,chipata,Kayla Wilson,69.5
2,STU02843,Christopher,Brown,Male,6.0,Grade 1,christopher_brown@gmail.com,0962209692,27 Mar 2023,1.30,CHIPATA,Vanessa Brown,70.3
92,STU00561,Marilyn,Becker,Female,6.0,Grade 1,marilyn_becker@outlook.com,+260-95-9250481,NaN,3.96,kabwe,NaN,96.7
76,STU01895,Steven,Williams,Female,6.0,Grade 1,stevenw52@school.edu.zm,260957565368,06-15-2020,2.07,Livingstone,Sean Williams,82.3
77,STU01078,Tyrone,Dennis,Female,6.0,Grade 1,tyrone.dennis470@outlook.com,0979016612,2021-03-19,1.42,Chingola,NaN,95.4
84,STU04665,Zoe,Turner,Male,7.0,Grade 1,zoet9@gmail.com,260964790292,12 Feb 2018,2.39,Chipata,Ryan Turner,66.4
67,STU03356,Christopher,Webb,Male,7.0,Grade 1,christopher.webb735@outlook.com,0975718099,27/01/2020,3.25,chingola,Alexis Webb,NaN
59,STU00735,Donna,Whitehead,Male,7.0,Grade 1,donna_whitehead@gmail.com,0963635975,09/05/2024,2.55,chipata,Angela Whitehead,65.8
73,STU04713,Kathryn,Shields,Female,7.0,Grade 1,kathryns57@school.edu.zm,+260-97-2662290,04/09/2020,2.83,Ndola,Wesley Shields,60.9
65,STU04520,Catherine,Curtis,Female,7.0,Grade 1,catherine.curtis822@yahoo.com,(96) 3170103,22 Feb 2023,2.05,Mongu,Robert Curtis,85.3
68,STU02367,William,Zuniga,Female,8.0,Grade 2,williamz39@gmail.com,(96) 9367470,2023/01/15,1.53,Ndola,Ann Zuniga,68.5
86,STU04009,Kathleen,Cole,Female,8.0,Grade 2,kathleen.cole957@outlook.com,0957848571,2023/08/23,1.69,Chingola,Isaac Cole,84.7
44,STU01837,Paige,Harper,Female,8.0,Grade 2,paigeh91@school.edu.zm,260963796316,NaN,3.39,Chipata,Shannon Harper,97.5
47,STU02049,Dominique,Bailey,Male,8.0,Grade 2,dominique.bailey325@outlook.com,260950050331,2020/04/13,1.83,LUSAKA,Kristen Bailey,94.6
22,STU00865,Nancy,Marks,Male,8.0,Grade 2,nancy.marks741@gmail.com,260956727792,2019/06/05,3.78,solwezi,Joshua Marks,70.6
26,STU02475,Wendy,Cole,Male,8.0,Grade 2,wendy_cole@school.edu.zm,+260-97-8903263,2020-07-20,3.76,NDOLA,Samuel Cole,65.4
13,STU04556,Douglas,Martinez,Female,8.0,Grade 2,douglasm94@yahoo.com,0952684383,22/12/2019,3.44,NaN,Anita Martinez,76.9
10,STU03820,Jason,May,Female,8.0,Grade 2,jason.may184@school.edu.zm,(96) 8241125,02-15-2024,3.04,Lusaka,Tara May,90.5
50,STU02779,Wendy,Dixon,Male,9.0,Grade 3,wendy.dixon771@outlook.com,0962069387,2024-01-14,3.37,MONGU,Jeremy Dixon,62.6
19,STU03756,Matthew,Brooks,Male,9.0,Grade 3,matthew_brooks@gmail.com,0957121403,05/06/2020,2.20,Mansa,Joseph Brooks,NaN
43,STU03638,Julie,Taylor,Male,9.0,Grade 3,julie.taylor60@yahoo.com,(97) 4563439,17/08/2021,1.77,Lusaka,Laura Taylor,81.8
80,STU02819,Linda,Johnson,Female,10.0,Grade 4,linda.johnson214@yahoo.com,0961479005,2020-03-23,3.33,Lusaka,Kathryn Johnson,63.2
55,STU00732,Susan,Bird,Male,10.0,Grade 4,susan_bird@gmail.com,(97) 2742095,2023-10-10,2.19,Mongu,Justin Bird,99.6
15,STU00145,Amanda,Shelton,Male,10.0,Grade 4,amanda_shelton@yahoo.com,(95) 6960666,07-03-2020,3.66,Kabwe,Gabriella Shelton,62.1
51,STU01060,Adrienne,Bauer,Female,10.0,Grade 4,adrienneb90@yahoo.com,NaN,02 Sep 2022,3.94,Chingola,Steven Bauer,78.4
97,STU02335,Zachary,Cook,Male,10.0,Grade 4,zachary_cook@outlook.com,(97) 5757898,05 Mar 2021,2.33,NaN,Heidi Cook,89.2

In [78]:
students_df.to_excel("Datasets/students_clean.xlsx", index = False)